### ISSUE TITLE
Spanish subbed animes

### ISSUE THREAD

**Issue by Berni04** [akuse-app/akuse#19]
Are there any plans to bring Spanish subtitles to the app. There's a huge Spanish speaking community (people from Spain and lots of countries from South America) that loves to watch anime and they could benefit a lot by using this app. 

I could understand bringing a bigger community to the app could make it more visible to any copyright infringements but lots of people would thank what you do.

**Comment by aleganza** [comment]
This app depends on a library, Consumet, where at the moment there are only some english providers and an italian one. So, to add more languages, someone should implement their respective providers to the library.

**Comment by ner00** [comment]
Is it possible to fetch subs from OpenSubtitles or any other reputable source and apply them with a customizable background color, fully or semi-opaque? I'm thinking a mechanism similar to what Stremio does... although this is not ideal, I wonder if it could enhance the experience for foreign speakers and make the app more appealing to wider audiences.

**Comment by aleganza** [comment]
It could be a thing but it would require more work. At the moment the only way to add more languages is to implement them to the library.
