### ISSUE TITLE
Jujutsu Kaisen - can't open next episode, no error note

### ISSUE THREAD

**Issue by BorniPL** [akuse-app/Akuse#20]
**Describe the bug**
Just started to watch Jujutsu Kaisen. Can't go to next episode, can't load 2nd episode manually.
I believe it's just hosting issue (because I could use these UI functionalities in other series), but it would be nice to have an error showing exactly what's going on.

**To Reproduce**
1. Load Jujutsu Kaisen
2. Click on episode 2
3. Nothing happens

Alternatively:
1. Load Jujutsu Kaisen episode 1
2. Click Next Episode button
3. Nothing happens

**Expected behavior**
The episode loads OR there is appropriate note why the episode isn't loading.

**Screenshots**

**Operative System:**
Windows 11 23H2

**Comment by aleganza** [comment]
Jujutsu Kaisen anime is actually pulling the Jujutsu Kaisen 0 Movie. Idk why, I'm gonna try to fix it today

**Comment by BorniPL** [comment]
Good to know 😅 Best time to start new anime, eh? 🤣

**Comment by aleganza** [comment]
fixed
