### ISSUE TITLE
Lack of Navigation Options

### ISSUE THREAD

**Issue by xKore123** [akuse-app/Akuse#21]
When using the anime streaming app, I encountered a bug related to episode selection. After clicking on the desired anime, a popup appears with the list of episodes. However, there is no option to input the episode number manually, and there are no navigation arrows to move to a specific episode. This becomes problematic when attempting to access episodes beyond the displayed ones, especially when there are only four episodes available and no "next" button.

**Comment by aleganza** [comment]
you can scroll episodes with the horizontal scrollbar at the bottom
![Cattura](https://github.com/akuse-app/Akuse/assets/73157384/605ff153-48d6-4ae2-be1b-30204286175c)
by the way I agree that an input or some type of pagination would be better.

**Comment by xKore123** [comment]
Love the app tho, great job!
