### ISSUE TITLE
weird issue where the players bugs out and shows the homepage for a split second

### ISSUE THREAD

**Issue by skyisthela** [akuse-app/Akuse#22]
**Describe the bug**
When watching a video the player bugs out and the homepage shows up for one frame

**To Reproduce**
1. Watch an episode
2. Homepage bugs in randomly

**Expected behavior**
Video plays without interference

**Screenshots**
As it's completely arbitrary and only for a moment it's hard to take one

**Operative System:**
Windows 10 20h2

**Comment by aleganza** [comment]
How often does it happen to you?

**Comment by skyisthela** [comment]
> How often does it happen to you?

basically all the time

**Comment by aleganza** [comment]
closing as it doesn't seem related to the app itself.
