### ISSUE TITLE
Error starting application

### ISSUE THREAD

**Issue by MatheusSFelix** [akuse-app/Akuse#23]
When I try to start the application it stops on this screen (image), I have already checked the data in clientData.js and it is correct, I have also given "npm run dist:win" and installed it, but even so a login screen does not appear (so I understand the code, I think this login screen was supposed to appear)

![image](https://github.com/akuse-app/Akuse/assets/31835013/788d623a-da34-45e6-8bcb-93a9b3987b32)

**Comment by aleganza** [comment]
In this step the app should fetch all the anime data and display it, so it seems to be a problem related to the anilist api (The login is not mandatory anymore so I exclude it as the reason of your bug).
I suggest you to open the DevTools and see if there is any error in console. and to check again if your clientData.js is 100% correct.

**Comment by aleganza** [comment]
yep electron apps are basically chrome instances so you can do that
cheers
