### ISSUE TITLE
Custom UI scaling 

### ISSUE THREAD

**Issue by ghazzor** [akuse-app/akuse#25]
![image](https://github.com/akuse-app/Akuse/assets/127341071/543fc551-7a02-411d-8a33-2c6540e98bdc)

stuff looks a little too big , the test size is fine but ui elements looks too big , a customizable size would be great
(i have a 1336x768 screen)

**Comment by aleganza** [comment]
what would you suggest?

**Comment by ghazzor** [comment]
You can just try setting the scaling to 90%
Then some further enhancements to fine tune the ui for 90% scale 

You can do like how telegram desktop allows you to set custom scaling

**Comment by ghazzor** [comment]
![photo_2023-12-22_20-46-21](https://github.com/akuse-app/Akuse/assets/127341071/f2b2b2b1-1cef-4fa2-a68e-eadd9ef29d6c)


> what would you suggest?
