### ISSUE TITLE
"Resume from ep. x" bug and suggestion

### ISSUE THREAD

**Issue by MatheusSFelix** [akuse-app/Akuse#28]
Version I'm using 0.3.0

When I click on the "Resume from ep. x" button the player does not load but if I click on any of the episodes in the list it works normally. And as a suggestion, I think it would be good to add an input to facilitate the search for episodes (although I think you could simulate a "filter" using the "List Editor").

![image](https://github.com/akuse-app/Akuse/assets/31835013/12a557f1-805d-491f-a79b-bea44e55338b)

![image](https://github.com/akuse-app/Akuse/assets/31835013/293f15b3-5393-44fb-8458-8736c2e037cf)

**Comment by aleganza** [comment]
just fixed the bug.
about the episodes filter, it's already planned in the next updates 👍
