### ISSUE TITLE
infinite loading 

### ISSUE THREAD

**Issue by darkerraven** [akuse-app/Akuse#30]
that's it infinite loading 
![Akuse_Sb04ynkmql](https://github.com/akuse-app/Akuse/assets/115076107/70c72fff-7b37-4328-b961-9872ca3e3609)

**Comment by aleganza** [comment]
did you open the app as a user or did you run it locally for development?

**Comment by darkerraven** [comment]
> did you open the app as a user or did you run it locally for development?

I don't know what you are saying but it works now

**Comment by aleganza** [comment]
nice
