### ISSUE TITLE
after clicking clicking the next episode button , on the next episode when i try to use arrow keys , instead of skipping a few seconds , it jumps to the next episode

### ISSUE THREAD

**Issue by ghazzor** [akuse-app/Akuse#33]
**Describe the bug**
as stated in the title

**To Reproduce**
1. click next episode
2. press arrow keys 
3. and you just skip that episode

**Expected behavior**
skip a few seconds

**Operative System:**
Windows 10
22H2

**Comment by ghazzor** [comment]
hmm , maybe it is because the the next episode button stays "selected" after clicking it , like it happened on old websites , so pressing some key presses the next episode button ?

**Comment by aleganza** [comment]
Next Episode can't stay selected as I made everything unselectable in the app
btw I just tested it but it doesn't happen to me.

**Comment by ghazzor** [comment]
> Next Episode can't stay selected as I made everything unselectable in the app btw I just tested it but it doesn't happen to me. does it happen with any show?

I am not the only one , it happened to me in zom 100 , but it happens in other shows as well

**Comment by aleganza** [comment]
I actually I see it happens with the Enter Key, but with arrow keys I can't reproduce it in any way. It happens sometimes or with any show?

**Comment by ghazzor** [comment]
> Actually I see it happens with the Enter Key, but with arrow keys I can't reproduce it in any way. Does it happen sometimes or with any show?

any show , and with arrow keys , i never tried enter (never pressed it even once) , but it does happen with arrow keys

**Comment by aleganza** [comment]
forgot about this issue, did you manage to solve it?

**Comment by ghazzor** [comment]
> forgot about this issue, did you manage to solve it?

Nah , I did not test or do anything , I have exams

**Comment by ghazzor** [comment]
this is not happening in v6

**Comment by aleganza** [comment]
perfect

**Comment by aleganza** [comment]
Just happened to me with spacebar, fixed in next update.

**Comment by ghazzor** [comment]
> Just happened to me with spacebar, fixed in next update.

hehe 

wen add hentai support

**Comment by ghazzor** [comment]
> Just happened to me with spacebar, fixed in next update.

hehe

**Comment by aleganza** [comment]
I read that 💀

**Comment by ghazzor** [comment]
> I read that 💀

i forgot what i wrote , tell in server
