### ISSUE TITLE
Some UI suggestions

### ISSUE THREAD

**Issue by agret** [akuse-app/Akuse#5]
The list scrolls horizontally, click and hold mouse down on a show and drag to the left/right and then release the mouse and it will open the show details for the one you first clicked to drag. Quite annoying that this happens constantly.

It would be great if you can put a little scrollbar below the horizontal lists so I can drag that across instead, feels more natural on a mouse to do this than to drag the shows like a touchscreen. Even better if the mouse scroll wheel can scroll through the shows when you have the mouse over the top of the scroll bar.

When you click on a show and the show info box pops up normally you can close these boxes by clicking into the surrounding black areas, on the app right now you must click on the little X to close the popup box.

In the show info box episode listing put a tick next to the ones you have already watched or some other visual way to see which one you are up to. Change "Resume" button to "Resume Episode 7". At the top next to "27 min/Ep" put another icon for how many episodes total in the series.

Can the show "box art" on the main screen get a little number for how many episodes the show is total / currently subbed / currently dubbed and what the anilist score is? This is how aniwatch shows it and is perfect (doesn't show score though):
![image](https://github.com/aleganza/Akuse/assets/568523/ec48d068-a572-437e-b727-487bda08c25d)

**Comment by aleganza** [comment]
All these suggestions are very interesting and I think they could improve the user UX a lot. I will surely implement them.

**Comment by Madagarian** [comment]
Additionally, the field where you input values when rating shows and adding episodes, can that be scroll wheel responsive so I can hover and scroll instead of clicking or typing? Can we have an option to create our own shelves/lists besides the auto-generated ones?

**Comment by MaiSan9999** [comment]
carino il progetto spero che continuerai a mantenerlo.

**Comment by aleganza** [comment]
Closing this since the app is getting full revamped, so some requested features have been added and other changed.
