### ISSUE TITLE
Videos fail to load (Gogo provider needs an update)

### ISSUE THREAD

**Issue by 0x96EA** [akuse-app/Akuse#50]
Hi it's been a while 👋

I have fixed this temporarily with a patch myself but you need to update @consumet/extensions once a new release is done which includes this PR https://github.com/consumet/consumet.ts/pull/485

When I have time I still want to give the mac login stuff a go.

**Comment by Vansh0134** [comment]
ye been happening since yesterday with me too

**Comment by aleganza** [comment]
gonna fix it tonight
