### ISSUE TITLE
hentai is fucked , while it shows up somewhere , but just does not work 

### ISSUE THREAD

**Issue by ghazzor** [akuse-app/Akuse#53]
**Describe the bug**
stated in title
(might be a scraper issue but oh well)
**To Reproduce**
1. open any hanime

**Expected behavior**
atleast give a warning before suddenly closing or working

**Operative System:**
Windows 10 22h2

**Comment by TwinAwakenings** [comment]
try disabling "Watch dubbed" in settings

**Comment by aleganza** [comment]
could you provide some titles you are getting issues with

**Comment by ghazzor** [comment]
> could you provide some titles you are getting issues with

Each one I tried is fucked , none of them works , you can try any Hanime which is present on anilist , I could not get any of them working

**Comment by TwinAwakenings** [comment]
Found the problem It's because current providers doesn't have hanime

**Comment by ghazzor** [comment]
> Found the problem It's because current providers doesn't have hanime

Yeah it's a scraper issue then

**Comment by aleganza** [comment]
closing this issue since as @TwinAwakenings says, hanime are not provided by Akuse sources, so it's not a fixable issue.

**Comment by ghazzor** [comment]
Sed lyf
