### ISSUE TITLE
[Feature] Add and arrange of seasons and  events

### ISSUE THREAD

**Issue by moha-b** [akuse-app/akuse#59]
![image](https://github.com/akuse-app/Akuse/assets/73842931/d299fa4a-3b27-4381-a357-3e4350e5af68)

### like here

![image](https://github.com/akuse-app/Akuse/assets/73842931/6d8055d4-3d7a-49b3-b4a9-962812bc0a0f)

**Comment by raliqala** [comment]
This  would be nice. I will work on it

**Comment by moha-b** [comment]
I appreciate it 🤟 ✨

**Comment by moha-b** [comment]
To clarify what I meant earlier - in the case of `Demon Slayer`, there is a movie that follows season one. Therefore, the correct sequence of events would be season one, then the movie, followed by season two, and then season three. 

Sorry for not being clear.

**Comment by tehrzky** [comment]
up. like movie/special and season tab. because if you click on trending and top anime it will only give you the s1 or the current season. it will be a QOL to easily to find the anime (since you cannot copy and paste inside the app)
