### ISSUE TITLE
On-Going Series Issues

### ISSUE THREAD

**Issue by agret** [akuse-app/Akuse#6]
Just watched episode 12 of a 24 episode series that is currently airing.

The anilist tracking still reports it as episode 11, i'm not sure if the code currently updates it when the episode is fully completed / clicked next episode but it should probably mark as complete when you have watched 90% of the episode.

**Comment by aleganza** [comment]
I think this could be a better algorithm, currently the app updates the progress when the "Next Episode" button is clicked, but the way you suggested looks much more natural.

**Comment by agret** [comment]
Just to add to this that if the show is currently airing and there is only 12 of 24 released so far when you press next episode on Episode 12 the title that says Episode 12 will change to Episode 13 and then if you click next again it says Episode 14 then Episode 15 etc when you keep clicking. Not sure if there is some way you can get the total episode released so far from anilist API and make it just stop playback when the episode ends / attempt to skip to next episode?

**Comment by agret** [comment]
In the home screen list of shows (if the anilist API allows it?) the current airing shows should be in a separate section to the ones that you have marked as currently watching and indicate if you are up to the current episode or not.

**Comment by aleganza** [comment]
I'll think about implementing this last suggestion, thank you.
