### ISSUE TITLE
[Bug] 🐞 Shrek Images every where

### ISSUE THREAD

**Issue by moha-b** [akuse-app/Akuse#60]
**Describe the bug**
Shrek images are unexpectedly present in many anime posters, which can be bothersome.

**To Reproduce**
open the app

**Screenshots**
![Screenshot 2024-04-02 011418](https://github.com/akuse-app/Akuse/assets/73842931/4b5bc923-0280-4e7e-8e0f-8e068b10b6c7)
![Screenshot 2024-04-02 011302](https://github.com/akuse-app/Akuse/assets/73842931/2f0a04c5-98dc-4c54-a03a-13ebd7262997)
![Screenshot 2024-04-02 011514](https://github.com/akuse-app/Akuse/assets/73842931/06227f97-7916-458a-b3fb-928fd73e52bb)
![Screenshot 2024-04-02 011032](https://github.com/akuse-app/Akuse/assets/73842931/4ca12020-d7b0-4624-b30b-16ec8b1827ef)

**Operative System:**
Windows 11

> Note
> *If this is for meme purposes, please close the issue.*

**Comment by aleganza** [comment]
bro wtf is this 💀😂

**Comment by moha-b** [comment]
u tell me 😆

**Comment by moha-b** [comment]
and who the hell is this 
![image](https://github.com/akuse-app/Akuse/assets/73842931/5a5f011c-bbfc-4b82-b4f3-d8b842fb7a21)

**Comment by aleganza** [comment]
just checked and it's Anilist 1st april fool, I thought you did all the edits for the same purpose.

**Comment by aleganza** [comment]
btw that's legolas

**Comment by aleganza** [comment]
nono it's a fool from the service I take the covers from,

**Comment by moha-b** [comment]
okay i was close to upload the record XD

**Comment by ghazzor** [comment]
Seems like a bug I want
