### ISSUE TITLE
 Suggestion: Utilize Separate Branch for React Porting

### ISSUE THREAD

**Issue by Nktech-Official** [akuse-app/Akuse#67]
## Summary
I'm writing to propose the use of a separate branch for porting Akuse to React. This approach would ensure the continued accessibility of the main branch codebase (or allow development on the main branch while maintaining a separate release branch).
## Benefits:
- **Preserves Buildability for Existing Users:** By keeping the main branch code functional, users can continue building their applications without encountering errors. Directly updating the main branch with porting changes could potentially break functionality for previous versions.
- **Maintains a Working Baseline:** A separate branch dedicated to the React porting effort would allow for a stable, last-working point to be maintained. This would be crucial for new users who can then build and utilize the application until the new React-ported version is officially released.

**Overall, this approach would promote:**

- Smoother Transition: Separating the porting work would minimize disruption for existing users.

- Enhanced Clarity: A clear distinction would be maintained between the ongoing porting efforts and the current, stable codebase.

- Improved Accessibility: New users would have a reliable point of entry to build and use Akuse until the React porting is complete.

I believe this suggestion would be beneficial for the project's development and user experience. I'm open to further discussion and any questions you might have.

**Comment by aleganza** [comment]
well it's a great idea, actually I didn't do it because it was late and I mistook tags for branches🥸
btw gonna do it

**Comment by aleganza** [comment]
any name suggestion? I was thinking to rename the current "old" and the react one "main"

**Comment by Nktech-Official** [comment]
My suggestion would be to make the last working code main and for react create a separate branch name e.g  `dev` , `react-port`, `react-migration` etc. Renaming the branch might break some things with existing forked branches so to avoid renaming the branches you could first create a separate branch with 
```
git checkout -b branch_name
```
push the brach by setting upstream like this 
```
git push --set-upstream origin branch_name
```
now this would be the new react branch then revert the main branch :
 switch back to main using the checkout command without -b 
then revert to last working commit and push the changes 
you can revert from either on local command line or on GitHub check the docs

**Comment by aleganza** [comment]
alright! thank you for your suggestion.
