### ISSUE TITLE
Oshi no Ko pulls wrong series

### ISSUE THREAD

**Issue by Madagarian** [akuse-app/akuse#7]
Attempting to watch [Oshi no Ko](https://anilist.co/anime/150672/Oshi-no-Ko/) instead pulls up [ROAD-TO-YOU](https://anilist.co/anime/100211/ROAD-TO-YOU). Oshi no Ko shows 11 episodes in Akuse, episodes 1-3 are linked to ROAD-TO-YOU 1-3 at ~3m each and 4-11 don't open anything.
![AkuseIssue7](https://github.com/aleganza/Akuse/assets/84937046/194e7f1b-7b5b-4d27-8c5e-bab92227c7ce)

**Comment by Madagarian** [comment]
This seems to be resolved now.

**Comment by aleganza** [comment]
fixed

**Comment by 0x96EA** [comment]
@aleganza This bug has returned again in the 1.0 release. 🙏
