### ISSUE TITLE
[UI] Bookmarks Tab Scrolling

### ISSUE THREAD

**Issue by Taxibutle** [akuse-app/Akuse#73]
If you have a bunch of animes set up as "Planned" (and possibly in the other rows), then you cannot scroll through all of them, and only see the 11 or so most recent ones.

Would also be cool to see "Current" animes in this list too, though they are already present on the main page.

**Comment by aleganza** [comment]
which version are you using? the old one or the react one

**Comment by Taxibutle** [comment]
I should be on the latest version (React?). The app auto-updated before I used it, so I can only assume it did. The first version I DL'd was the first version to have auto-update, then I updated with that.

**Comment by aleganza** [comment]
alright. anyway with the new app rebranding all your issues should be already fixed, so I'll close this now and you'll tell me, when I'll release the version, if they persist.
