### ISSUE TITLE
it's not playing any videos

### ISSUE THREAD

**Issue by Light7654** [akuse-app/akuse#76]
![Screenshot 2024-05-31 175157](https://github.com/akuse-app/Akuse/assets/87866912/9067e628-3471-4f72-8f11-c7c6b69c3651)

**Comment by aleganza** [comment]
will indagate

**Comment by aleganza** [comment]
as I have seen on the discord server, this is probably a location based issue. at the moment I wouldn't know how to fix it until someone with this problem will look into the code and the errors it gives.☹

**Comment by d7eeem** [comment]
in my case the source is blocked. using vpn or proxy fixed it.
