### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by Rushabh178** [akuse-app/akuse#79]
![Screenshot 2024-06-08 190139](https://github.com/akuse-app/Akuse/assets/128458296/9362f63d-da2d-476f-9685-36fabe8e6593)
Where ever I "npm start" it throws me an error as follows
Module '"../modules/clientData"' has no exported member 'clientData'.
can anyone please help

**Comment by aleganza** [comment]
you didn't follow the readme guideline for creating the anilist client😭😭

**Comment by aleganza** [comment]
you can check now
