### ISSUE TITLE
Grey Screen After Log-on

### ISSUE THREAD

**Issue by Taxibutle** [akuse-app/Akuse#9]
**Describe the bug**
After logging in to Anilist, it says that it is successful and closes the authentication window. However, only a grey screen is visible on the application. 

**To Reproduce**
1. Log in to Anilist, which closes the authentication window
2. Grey Screen

**Expected behavior**
Should start the application and such

**Screenshots**
![image](https://github.com/akuse-app/Akuse/assets/25257631/453ea8f0-493d-4240-b66f-11c5ddc9aff8)

![image](https://github.com/akuse-app/Akuse/assets/25257631/6748bc80-eeee-4e60-a567-30046822935e)

![image](https://github.com/akuse-app/Akuse/assets/25257631/960fd33c-2cc1-4e9b-8e15-afe2d42a9e8c)

**Operative System:**
Windows 10, latest update

**Additional context**
This was installed through the latest release (Beta 1.0). I didn't have an Anilist account so I had made one prior to logging in, which worked fine as per image one, but now it's just grey. No errors, the program is responding, and is still visible in Task Manager.

**Comment by Taxibutle** [comment]
Please ignore, refer to one of the closed issues for the problem.

As it says there, the issue was that my Anilist account, since it was brand new, didn't load any shows or anything so it was completely blank, simply add a few shows and then relaunch the app for it to work.

**Comment by aleganza** [comment]
This bug will be fixed in the next version.
